### PR TITLE
addon updates for v1.4.0-rc2

### PR DESCRIPTION
**Pull request by ibrokethecloud**
PR introduces version updates for 
* vm-import-controller
* pcidevices controller
* nvidia-driver-runtime

### CODE REVIEW

**Review by tserong — COMMENTED** [review]
LGTM, except, if the vm-import-contoller image got a version bump, shouldn't the chart also get a version bump?

**Comment by ibrokethecloud** [comment]
there was no change in the chart, only an image change to update include sle bci 15.6 as the base image.

**Review by tserong — APPROVED** [review]
OK, I can see how that works :-)  I just thought it was weird that the last vm-import-controller release we have in the charts repo is https://github.com/harvester/charts/commit/36857bc9839c4d5f49b16a078b6cc3314db56337 (i.e. there's nothing there to pick up v0.4.1), but that's a separate issue.

**Review by Vicente-Cheng — APPROVED** [review]
thanks for the update!

**Comment by ibrokethecloud** [comment]
@mergifyio backport v1.4

**Pull request merged**
